// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"name":"Login","path":"/user","layout":false,"id":"1"},"2":{"path":"/user/login","parentId":"1","id":"2"},"3":{"name":"Register","path":"/user","layout":false,"id":"3"},"4":{"path":"/user/register","parentId":"3","id":"4"},"5":{"name":"Welcome Page","path":"/welcome","icon":"smile","parentId":"ant-design-pro-layout","id":"5"},"6":{"icon":"robot","path":"/add_chart","name":"Chart Generation (Sync)","parentId":"ant-design-pro-layout","id":"6"},"7":{"icon":"robot","path":"/add_chart_async","name":"Chart Generation (Async)","parentId":"ant-design-pro-layout","id":"7"},"8":{"icon":"pieChart","path":"/chart","name":"Chart Page","parentId":"ant-design-pro-layout","id":"8"},"9":{"icon":"pieChart","path":"/chartDetail/:id","name":"Chart Details","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"9"},"10":{"name":"Personal Information","path":"/user/manager","icon":"user","parentId":"ant-design-pro-layout","id":"10"},"11":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"11"},"12":{"path":"*","layout":false,"id":"12"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import( './EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__User__Register__index" */'@/pages/User/Register/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Chart__addChart__index" */'@/pages/Chart/addChart/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Chart__addChartAsync__index" */'@/pages/Chart/addChartAsync/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Chart__myChart__index" */'@/pages/Chart/myChart/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Chart__myChartDetail__index" */'@/pages/Chart/myChartDetail/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__User__Manager__index" */'@/pages/User/Manager/index.tsx')),
'11': React.lazy(() => import( './EmptyRoute')),
'12': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/kanavi/personalproject/xingbi-fontend-master/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'/Users/kanavi/personalproject/xingbi-fontend-master/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
