// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/kanavi/personalproject/xingbi-fontend-master/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import RobotOutlined from '/Users/kanavi/personalproject/xingbi-fontend-master/node_modules/@ant-design/icons/es/icons/RobotOutlined';
import PieChartOutlined from '/Users/kanavi/personalproject/xingbi-fontend-master/node_modules/@ant-design/icons/es/icons/PieChartOutlined';
import UserOutlined from '/Users/kanavi/personalproject/xingbi-fontend-master/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { SmileOutlined, RobotOutlined, PieChartOutlined, UserOutlined };
